In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
print(a)

[1 2 3]


In [10]:
sam=np.array([(3,4,5),(8,7,6)])

In [8]:
print(sam)

[[3 4 5]
 [8 7 6]]


In [10]:
sam2=np.transpose(sam)

In [11]:
print(sam2)

[[3 8]
 [4 7]
 [5 6]]


In [12]:
sam2.ravel()

array([3, 8, 4, 7, 5, 6])

In [13]:
sam2.reshape(3,2)

array([[3, 8],
       [4, 7],
       [5, 6]])

In [7]:
sam2=np.zeros((3,2))

In [8]:
print(sam2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
np.append(sam2,sam)

array([0., 0., 0., 0., 0., 0., 3., 4., 5., 8., 7., 6.])

In [12]:
np.insert(sam2,3,6)

array([0., 0., 0., 6., 0., 0., 0.])

In [13]:
np.delete(sam2,3)

array([0., 0., 0., 0., 0.])

In [14]:
np.random.random((3,3))

array([[0.17268706, 0.82729379, 0.79936047],
       [0.97854873, 0.52980623, 0.45873452],
       [0.23758015, 0.19199598, 0.71237849]])